In [5]:
import sklearn
import pandas as pd
import numpy as np
# conda install -c conda-forge xgboost
import xgboost
# https://drive.google.com/file/d/1npdCLF0KMkTspBH-E0TSaNvmc9TEuSiL/view?usp=sharing
# conda install -c conda-forge lightgbm
import lightgbm

In [6]:
print(sklearn.__version__)
print(pd.__version__)
print(np.__version__)
print(xgboost.__version__)
print(lightgbm.__version__)

1.3.0
2.0.3
1.24.3
1.7.3
3.3.5


### Numpy
- 머신러닝 애플리케이션에서 데이터 추출, 가공, 변환과 같은 데이터 처리 부분을 담당한다.
- 넘파이 기반의 사이킷런을 이해하기 위해서는 넘파이는 필수이다.
- 사이킷런은 직관적이고 간결하기 때문에 상대적으로 개발하기 쉽지만 넘파이는 양도 많고 배워야 할 것도 많다.
- 넘파이 전체를 다 이해하고 공부하는 것은 머신러닝을 포기하게 만들기 때문에 기본 문법과 중요 API만 이해하는 것이 전략적으로 좋다.

### ndarray
- N차원(Dimension) 배열 객체
- 파이썬 list를 array() 메소드에 전달하면 ndarray로 변환되고 다양하고 편리한 기능들을 사용할 수 있게 된다.
![](./images/numpy1.png)

In [7]:
import numpy as np

In [39]:
ndarray1 = np.array([1, 2, 3])
ndarray2 = np.array([[1, 2, 3], [4, 5, 6]])
ndarray3 = np.array([[[1, 2, 3]]])
print(type(ndarray1), ndarray1, sep="\n")
print(type(ndarray1), ndarray2, sep="\n")

# shape: 차원을 알 수 있으며, 각 차원별 개수를 나타냄
print(ndarray1.shape[0:2])
print(ndarray2.shape)

# ndim: 차원만 나타냄
print(ndarray1.ndim)

<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
(3,)
(2, 3)
1


### astype()
- ndarray에 저장된 요소의 타입을 변환 시킬 때 사용한다.
- 대용량 데이터 처리 시, 메모리 절약을 위해 사용한다.

In [46]:
ndarray1 = np.array([1, 2, 3])
ndarray2 = np.array([4, 5, 6])

print(type(ndarray1))
print(ndarray1.dtype)

ndarray1_int8 = ndarray1.astype(np.int8)
print(ndarray1_int8.dtype)

ndarray1_float16 = ndarray1.astype(np.float16)
print(ndarray1_float16.dtype)
print(ndarray1_float16)

ndarray2_int16 = ndarray2.astype('int16')
print(ndarray2_int16.dtype)

<class 'numpy.ndarray'>
int64
int8
float16
[1. 2. 3.]
int16


### ndarray의 axis
- 축의 방향성을 표현할 때 axis로 표현할 수 있다.
- 2차원(행, 열)일 경우 순서대로 행: axis 0(위에서 아래로), 열: axis 1(왼쪽에서 오른쪽)이다.
- 3차원(면, 행, 열)일 경우 순서대로 면: axis 0(뒤에서 앞으로, 행: axis 1(위에서 아래로), 열: axis 2(왼쪽에서 오른쪽)이다.
![](./images/numpy2.png)

### arange(), zeros(), ones()
- ndarray의 요소를 원하는 범위의 연속값, 0또는 1로 초기화할 때 사용한다.

In [55]:
# 0~9까지 1차원
ndarray = np.arange(0, 10)
print(ndarray, ndarray.dtype, ndarray.shape)

# 2행 3열 요소 모두 0으로 초기화
ndarray = np.zeros((2,3))
print(ndarray, ndarray.dtype, ndarray.shape)

# 1차원 3칸 배열 요소 모두 1로 초기화
# ndarray = np.ones(3) 아래와 똑같지만 나중에 아래 처럼쓰는게 좋을수 있어서 
ndarray = np.ones((3,))
print(ndarray, ndarray.dtype, ndarray.shape)

# 요소 타입 정수로 변환
ndarray_int8 = ndarray.astype(np.int8)
print(ndarray_int8, ndarray_int8, ndarray_int8.shape)

[0 1 2 3 4 5 6 7 8 9] int64 (10,)
[[0. 0. 0.]
 [0. 0. 0.]] float64 (2, 3)
[1. 1. 1.] float64 (3,)
[1 1 1] [1 1 1] (3,)


### reshape()
- ndarray의 기존 shape를 다른 shape로 변경한다

In [62]:
ndarray1 = np.arange(8)
print(ndarray1, ndarray1.shape)

print("=" *30)

ndarray2 = ndarray1.reshape(2, 4)
print(ndarray2, ndarray2.shape)

print("=" *30)
#axis -에 -1을 작성하면, 자동으로 열 개수로 나누어 맞춰진다. 직접 계산해서 작성하는 번거로움을 줄여준다.
ndarray3 = ndarray1.reshape(-1, 2)
print(ndarray3, ndarray3.shape)


print("=" *30)
ndarray4 = ndarray1.reshape(4, -1)
print(ndarray4, ndarray4.shape)

[0 1 2 3 4 5 6 7] (8,)
[[0 1 2 3]
 [4 5 6 7]] (2, 4)
[[0 1]
 [2 3]
 [4 5]
 [6 7]] (4, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]] (4, 2)


### Indexing
- 특정 위치의 데이터를 가져오는 것

1. 위치 인덱싱(Location indexing): 전달한 위치(인덱스)의 값 한 개 추출
2. 슬라이싱(Slicing): 시작 위치와 종료 위치에 해당하는 ndarray 추출
3. 팬시 인덱싱(Fancy indexing): list를 전달하여 한 번에 여러 요소를 추출, 특정 위치 값들을 콕 찝어서 추출
4. 불린 인덱싱(Boolean indexing): True인 위치릐 ndarray 추출

In [77]:
# 1-1. 1차원 위치 인덱싱(Location indexing)
# 2부터 10까지 순서대로 요소를 갖는 1차원 ndarray
ndarray = np.arange(start=2, stop=11)
ndarray

data = ndarray[2]
print(data, type(data))

data = ndarray[-1]
print(data, type(data))


data = ndarray[-2]
print(data, type(data))


ndarray[-1] = 100
print(ndarray)


4 <class 'numpy.int64'>
10 <class 'numpy.int64'>
9 <class 'numpy.int64'>
[  2   3   4   5   6   7   8   9 100]


In [81]:
# 1-2. 2차원 위치 인덱싱(Location indexing)
ndarray1 = np.arange(start=1, stop=10)
ndarray2 = ndarray1.reshape((3, -1))
print(ndarray2)

print(ndarray2[1, 0])
print(ndarray2[1, 1])
print(ndarray2[2, 0])
print(ndarray2[2, 1])
print(ndarray2[0], ndarray2[0].shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
4
4
4
4
4


In [89]:
# 2-1. 1차원 슬라이싱(Slicing)

ndarray1 = np.arange(start=2, stop=10, step=2)
print(ndarray1)

print(ndarray1[:3], ndarray1[:3].shape)
print(ndarray1[3:], ndarray1[3:].shape)
print(ndarray1[:])
print(ndarray1[-4:])
print(ndarray1[-2::-1])

[2 4 6 8]
[2 4 6] (3,)
[8] (1,)
[2 4 6 8]
[2 4 6 8]
[6 4 2]


In [91]:
# 2-2. 2차원 슬라이싱(Slicing)

ndarray1 = np.arange(start=1, stop=28)
print(ndarray1)

print("=" * 30)

ndarray2 = ndarray1.reshape((-1, 3))
print(ndarray2)

print("=" * 30)

print(ndarray2[:3, :2])

print("=" * 30)

print(ndarray2[4:9])

print("=" * 30)

print(ndarray2[4:, :])

print("=" * 30)

print(ndarray2[:])

print("=" * 30)

print(ndarray2[-2:-1, 0:2])

print("=" * 30)

print(ndarray2[::-1])

print("=" * 30)

print(ndarray2[::-1, ::-1])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]]
[[1 2]
 [4 5]
 [7 8]]
[[13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]]
[[13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]]
[[22 23]]
[[25 26 27]
 [22 23 24]
 [19 20 21]
 [16 17 18]
 [13 14 15]
 [10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]
[[27 26 25]
 [24 23 22]
 [21 20 19]
 [18 17 16]
 [15 14 13]
 [12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]


In [92]:
# 3. 팬시 인덱싱(Fancy indexing)

ndarray1 = np.arange(start=1, stop=21)
ndarray2 = ndarray1.reshape((4, 5))
print(ndarray2)

print(ndarray2[[0, 1, 3], 2:5])
print(ndarray2[[0, 1]])

# 2차원 ndarray에서 행과 열 모두 팬시 인덱싱을 사용하면, 해당 좌표의 열백터를 가져온다.
# ndarray2[[x1, x2], [y1, y2]] : (x1, y1), (x2, y2) : [x, y]
print(ndarray2[[1, 2], [1, 3]])
print(ndarray2[[3, 2, 1], [1, 2, 4]])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 3  4  5]
 [ 8  9 10]
 [18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 7 14]
[17 13 10]


In [113]:
# 4. 불린 인덱싱(Boolean indexing)
ndarray1 = np.arange(start=1, stop=101, step=3)
print(ndarray1 % 5 == 0)
print(ndarray1[ndarray1 % 5 == 0])

ndarray1 = np.arange(3)
print(ndarray1)
print(ndarray1[[False, True, False]])

[False False False  True False False False False  True False False False
 False  True False False False False  True False False False False  True
 False False False False  True False False False False  True]
[ 10  25  40  55  70  85 100]
[0 1 2]
[1]


### 정렬
- 모두 오름차순 정렬이며, 내림차순은 오름차순 정렬 후 [::-1]을 붙여 사용한다.
1. np.sort(ndarray) : 전달한 기존 행렬은 그대로 놔둔 채 새롭게 정렬된 행렬을 리턴한다.
2. np.sort(ndarray, axis=n) : 전달한 축(axis)을 기준으로 정렬한다.
3. ndarray.sort() : 기존 행렬을 정렬하며, 리턴은 없다.
4. np.argsort(ndarray) : 요소 정렬 후 원래 인덱스(정렬 전 인덱스)를 리턴한다.

In [94]:
# np.sort(ndarray)

original_ndarray = np.array([0, 4, 2, 5])

sorted_ndarray = np.sort(original_ndarray)
print(f"원본 배열: {original_ndarray}")
print(f"정렬된 배열: {sorted_ndarray}")

원본 배열: [0 4 2 5]
정렬된 배열: [0 2 4 5]


In [95]:
# np.sort(ndarray, axis=n)

ndarray1 = np.array([i for i in range(20, 0, -2)])
ndarray2 = ndarray1.reshape(2, -1)
print(f"원본 \n{ndarray2}")

ndarray2[0, 1] = 3
sorted_ndarray_axis0 = np.sort(ndarray2, axis=0)
print(f"axis0 정렬 \n{sorted_ndarray_axis0}")

sorted_ndarray_axis1 = np.sort(ndarray2, axis=1)
print(f"axis1 정렬 \n{sorted_ndarray_axis1}")

원본 
[[20 18 16 14 12]
 [10  8  6  4  2]]
axis0 정렬 
[[10  3  6  4  2]
 [20  8 16 14 12]]
axis1 정렬 
[[ 3 12 14 16 20]
 [ 2  4  6  8 10]]


In [97]:
# ndarray.sort()

original_ndarray = np.array([1, 2, 0, 4])
original_ndarray.sort()

print(f"원본 배열: {original_ndarray}")
print(f"내림 차순: {original_ndarray[::-1]}")

원본 배열: [0 1 2 4]
내림 차순: [4 2 1 0]


In [98]:
# np.argsort(ndarray)

original_ndarray = np.array([0, 3, 2, 6])
sorted_indices = np.argsort(original_ndarray)
print(f'정렬 후 원래 인덱스: {sorted_indices}', type(sorted_indices))

sorted_indices_desc = sorted_indices[::-1]
print(f'정렬 후 원래 인덱스: {sorted_indices_desc}', type(sorted_indices_desc))

정렬 후 원래 인덱스: [0 2 1 3] <class 'numpy.ndarray'>
정렬 후 원래 인덱스: [3 1 2 0] <class 'numpy.ndarray'>


In [100]:
cars = np.array(['Lamborghini', 'Mclaren', 'Benz', 'Bentley', 'The New Morning'])
zero100 = np.array([2.8, 2.9, 5.2, 3.7, 13.5])

sorted_indices = np.argsort(zero100)
print(f'정렬 후 zero100 인덱스: {sorted_indices}')
print(cars[sorted_indices])

정렬 후 zero100 인덱스: [0 1 3 2 4]
['Lamborghini' 'Mclaren' 'Bentley' 'Benz' 'The New Morning']


### 벡터
- 벡터는 공간에서 한 점을 나타낸다.
- 벡터는 원점으로부터 상대적 위치를 표현한다.
- 벡터는 서로 같은 모양을 가지고 있다면 덧셈, 뺄셈을 계산할 수 있다.
- 두 벡터의 덧셈 혹은 뺄셈은 다른 벡터를 기준으로 상대적 위치 이동을 표현한다.

### 벡터의 NORM
- 원점에서부터의 거리를 말한다.
- L<sub>1</sub> - 노름은 각 성분의 변화량의 절대값을 모두 더한다.
- L<sub>2</sub> - 노름은 피타고라스의 정리를 이용해 유클리드 거리를 계산한다.

### 행백터와 열백터
<img src="./images/vector.png" width="500" style="margin-left: 20px">

### 내적(Dot product)
- 두 벡터의 성분들의 곱의 합.
- 벡터의 길이 계산, 두 개의 벡터가 수직인지, 평행하는 지, 둘 사이의 각이 얼마인지 등의 정보를 알아낼 수 있다.

In [114]:
# (n, m) * (n, m) = (n, m)
import numpy as np

ndarray1 = np.arange(1, 7).reshape((2, 3))
ndarray2 = np.arange(1, 7).reshape((2, 3)) + 2

print(ndarray1)
print(ndarray2)

ndarray3 = ndarray1 * ndarray2
print(ndarray3)

[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [6 7 8]]
[[ 3  8 15]
 [24 35 48]]


In [115]:
# (n, m).dot((m, k)) = (n, k)

ndarray1 = np.arange(1, 7).reshape((2, 3))
ndarray2 = np.arange(1, 7).reshape((2, 3)) + 2

print(ndarray1)
print(ndarray2.T)

ndarray3 = ndarray1.dot(ndarray2.T)
print(ndarray3)

ndarray4 = ndarray1@ndarray2.T
print(ndarray4)

[[1 2 3]
 [4 5 6]]
[[3 6]
 [4 7]
 [5 8]]
[[ 26  44]
 [ 62 107]]
[[ 26  44]
 [ 62 107]]


### 선형대수(Linear Algebra)
#### 📌Linear Algebra는 "리니어 알제브라"로 발음한다.
- 선형 방정식을 풀기 위해 배우는 학문이다.
- y = 3x일 경우, 3을 곱한 만큼만 x가 변한다.
- y = 2x<sup>2</sup>일 경우, 2를 곱했는데, 2만큼이 아닌 전혀 다르게 값이 크게 변한다.
- 미지수가 한 개라면 예측하기 쉬우나 미지수가 2개 이상이라면 그 만큼의 방정식이 더 필요하다.
- 이러한 연립 방정식을 표현할 때 쉽게 표현하기 위해서 선형대수를 배운다.
- 결과적으로 선형대수는 선형을 가지는 방정식(벡터)들의 연산을 통해 방정식의 해를 구하는 학문이다.

### 전치행렬
- 행과 열을 반대로 바꾸는 작업  

### 행렬내적  
- 행렬끼리 곱한 후 합을 구하는 작업  

### 역행렬
- 행렬의 역수
- 역수란, 곱셈에 대한 항등원이 1이 나오게 하는 수이며, A행렬의 역수는 A<sup>-1</sup>로 표기한다.

### 📌 연립방정식을 쉽게 정리하고 풀기 위해 선형대수를 사용한다.

k = [[k<sub>1</sub>], [k<sub>2</sub>]]  
A = [[x<sub>1</sub>, x<sub>2</sub>], [y<sub>1</sub>, y<sub>2</sub>]]  
w = [[w<sub>1</sub>], [w<sub>2</sub>]]  

1. k<sub>1</sub> = x<sub>1</sub>w<sub>1</sub> + x<sub>2</sub>w<sub>2</sub>
2. k<sub>2</sub> = y<sub>1</sub>w<sub>1</sub> + y<sub>2</sub>w<sub>2</sub>
3. k = Aw

#### 위와 같이 선형대수를 사용하면, 최소한의 타이핑으로 대량의 데이터를 쉽게 계산할 수 있게 된다.

In [111]:
A = np.array([1, 2, 3, 4]).reshape(2, 2)
w = np.array([5, 6]).reshape(2, 1)

print(A, w, sep="\n")
print("=" * 30)
print(np.dot(A, w))

[[1 2]
 [3 4]]
[[5]
 [6]]
[[17]
 [39]]


In [1]:
ndarray1 = np.arange(1, 5).reshape(2, 2)
ndarray1_T = ndarray1.T
print(ndarray1, ndarray1_T, sep="\n")

ndarray2 = np.arange(1, 33).reshape(4, -1)
ndarray2_T = ndarray2.T
print(ndarray2, ndarray2_T, sep="\n")

NameError: name 'np' is not defined

### 선형대수에서 투영을 사용하는 이유
- 과결정계(Overdetermined system)의 경우 미지수보다 많은 방정식이 있는 연립방정식으로서 보통 해가 존재하지 않는다.
- 그 이유는 선형결합(일차결합)이 불가능하기 때문에 해를 구할 수 없다.
- 선형결합(일차결합)이란 벡터들의 결합을 의미한다. 
- Aw=k일 경우 k가 반드시 A의 열공간에 존재해야 한다.
- A의 열의 개수를 m, 각 원소(성분, 요소)의 개수를 n이라 하면,  
m차원 벡터 n개의 선형결합으로 만들어지는 A의 열공간은 m차원 공간에 존재하는 n차원이다.
- 아래의 예시를 보면, A의 열의 개수는 2(m), 원소(성분, 요소, n)의 개수는 3이므로 3차원 공간에 존재하는 2차원 평면이다.  
이는 열공간이 2차원 평면이라는 뜻이고, 해(k)를 구하기 위한 선형결합(일차결합)이 없다는 의미이다.
<img src="./images/projection1.png" width="350" style="margin-left: 0px; margin-bottom: 20px"> 

In [2]:
A = np.array([[1, 1, 1], [1, 2, 3]])
k = np.array([[1, 2, 2]]).T
print(np.dot(np.linalg.inv(A), k))

NameError: name 'np' is not defined

### 🚩따라서, 열공간에 존재하지 않는 해를 구할 때에는 <br><br>가장 근접한 해를 구하기 위해 투영을 하여 열공간으로 넣어주고 이를 투영행렬로 계산한다.
<img src="./images/projection2.png" width="150" style="margin-left: 0px; margin-bottom: 20px">  

#### 이를 이용해서 정확한 해를 구하는 것이 아닌 가장 가까운 해를 구하는 최소자승법(least square method)을 사용한다.  
- 각 방정식의 제곱 값을 모두 더한 뒤 미분한다.  
> E<sup>2</sup> = (x + y - 1)<sup>2</sup> + (x + 2y - 2)<sup>2</sup> + (x + 3y - 2)<sup>2</sup>  
> ( x + y - 1) + (x + 2y - 2) + (x + 3y - 2) = 0  
> 3x + 6y = 5   
> 6y = -3x + 5
> <img src="./images/projection3.png" width="350" style="margin-left: 0px; margin-bottom: 20px"> 