### ndarray Task

In [23]:
import numpy as np

#1 1~10까지의 요소를 ndarray에 담는다.
# ndarray1 = np.array([i for i in range(1, 11)])
ndarray1 = np.array(list(range(1, 11)))
print(type(ndarray1), ndarray1.shape, ndarray1.ndim, ndarray1.dtype, sep="\n")

print("=" * 50)

#2 3행 2열 list를 ndarray에 담고 각 요소는 순서대로 6, 5, 4, 3, 2, 1을 담는다.
python_list = []
python_list.append([6 - i for i in range(2)])
python_list.append([4 - i for i in range(2)])
python_list.append([2 - i for i in range(2)])

ndarray2 = np.array(python_list)
print(type(ndarray2), ndarray2.shape, ndarray2.ndim, ndarray2.dtype, sep="\n")

print("=" * 50)

#3 4행 1열 ndarray, 순서대로 10, 8, 6, 4를 담는다(transpose, 전치).
ndarray3 = np.array([[(5 - i) * 2 for i in range(4)]]).T
print(type(ndarray3), ndarray3.shape, ndarray3.ndim, ndarray3.dtype, sep="\n")

print("=" * 50)

# #1에서 제작된 ndarray의 요소 타입 출력
print(ndarray1.dtype)

print("=" * 50)

# #1에서 제작된 ndarray의 차원 출력
print(ndarray1.shape)

print("=" * 50)

# #2에서 제작된 ndarray의 요소 타입을 float으로 변환
ndarray2_float32 = ndarray2.astype(np.float32)
print(ndarray2_float32)

print("=" * 50)

# #2에서 제작된 ndarray의 차원 출력
print(ndarray2.shape)

print("=" * 50)

# #3에서 제작된 ndarray의 요소 타입을 int8로 변환
ndarray2_int8 = ndarray2.astype(np.int8)
print(ndarray2_int8.dtype, ndarray2_int8, sep="\n")

print("=" * 50)

# #3에서 제작된 ndarray의 요소에 5씩 더하기
ndarray3_result = ndarray3 + 5
print(ndarray3_result)

print("=" * 50)

# #3에서 제작된 ndarray의 차원 출력
print(ndarray3.shape)

<class 'numpy.ndarray'>
(10,)
1
int32
<class 'numpy.ndarray'>
(3, 2)
2
int32
<class 'numpy.ndarray'>
(4, 1)
2
int32
int32
(10,)
[[6. 5.]
 [4. 3.]
 [2. 1.]]
(3, 2)
int8
[[6 5]
 [4 3]
 [2 1]]
[[15]
 [13]
 [11]
 [ 9]]
(4, 1)


### arange, zeros, ones Task

In [29]:
# axis 0이 10인 shape이면서 모든 원소가 0, dtype은 int32 인 ndarray 만들기
ndarray = np.zeros((10, ), dtype=np.int32)
print(ndarray, ndarray.dtype, ndarray.shape)

# axis 0이 3, axis1이 4인 shape이면서 모든 원소가 1인 ndarray 만들기
ndarray = np.ones((3, 4), dtype=np.int8)
print(ndarray, ndarray.dtype, ndarray.shape)

# axis 0이 5, 각 요소가 0~4인 ndarray 만들기
ndarray = np.arange(5)
print(ndarray, ndarray.dtype, ndarray.shape)

[0 0 0 0 0 0 0 0 0 0] int32 (10,)
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] int8 (3, 4)
[0 1 2 3 4] int32 (5,)


### reshape Task

In [41]:
ndarray1 = np.arange(start=0, stop=16)
ndarray1

print("=" * 50)

# 2 Dimension, axis 1은 2로 변경
ndarray2 = ndarray1.reshape((-1, 2))
print(ndarray2.shape, ndarray2, sep="\n")

print("=" * 50)

# 2 Dimension, axis 0은 8로 변경
ndarray3 = ndarray1.reshape((8, -1))
print(ndarray3.shape, ndarray3, sep="\n")

print("=" * 50)

# 3 Dimension으로 변경
ndarray4 = ndarray1.reshape((4, 2, -1))
print(ndarray4.shape, ndarray4, sep="\n")

print("=" * 50)

# ndarray3을 axis 1이 1인 2차원 ndarray로 변환
ndarray5 = ndarray4.reshape((-1, 1))
print(ndarray5.shape, ndarray5, sep="\n")

print("=" * 50)

# ndarray3을 1 Dimension으로 변환
ndarray6 = ndarray4.reshape((-1,))
print(ndarray6.shape, ndarray6, sep="\n")

(8, 2)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
(8, 2)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
(4, 2, 2)
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]
(16, 1)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]
(16,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


### Indexing Task